# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iNvBPOgcqvO2zv-TGkuupeJZNt9cwaOT
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/tbii-qazn-mt-balans-dt_bd_018.csv")

df

df.shape

import chardet
with open("/content/tbii-qazn-mt-balans-dt_bd_018.csv", 'rb') as rawdata:
    result = chardet.detect(rawdata.read())

result

df.fillna(method="ffill", inplace=True)

df.drop_duplicates(inplace=True)

df.isna().sum()

df.drop("Unnamed: 1", axis=1, inplace=True)

stcol = df.select_dtypes(include=['object']).columns
a = 0
for col in stcol:
    a+=(df[col]=='-').sum()
    df[col] = df[col].replace('-', '0').astype(float)

plt.figure(figsize=(10, 5))
plt.plot(df['Year'], df['Transformasiya sektorunun məsrəfi'])

plt.plot(df['Year'], df['İstehsal'], marker='o')
plt.plot(df['Year'], df['İxrac'].abs(), marker='x')
plt.title('Energy Production and Export Trends')
plt.xlabel('Year')
plt.ylabel('Amount')
plt.grid()

sns.heatmap(df.drop(columns=['Year']).corr(), annot=True)
plt.title('Metric Correlation Heatmap')